name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "event-check" ]
  pull_request:
    branches: [ "master" ]
    types:
      - closed

  # 3
  workflow_dispatch:

# 4
jobs:

#  version:
#    name: Create version number
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Get version txt
#        uses: actions/download-artifact@v2
#        with:
#          name: gitversion
#      - name: Create new file without newline char from version.txt
#        run: tr -d '\n' < version.txt > version1.txt
#
#      - name: Read version
#        id: version
#        uses: juliangruber/read-file-action@v1
#        with:
#          path: version1.txt
#
#      - name: Update version in YAML
#        run: sed -i 's/99.99.99+99/${{ setps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml


  # 5
  build:
    # 6
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    # 7
    steps:
      #8
      - uses: actions/checkout@v3

      #9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Dart format
        run: dart format .

      - name: Commit and push indentation
        run: |
          git config user.name "sanesh27"
          git config user.email "sanish.maharjan27@gmail.com"
          git add .
          git commit -m "Update: code format and version update"
          
          echo "Before: ${{ github.event.before }}"
          echo "After: ${{ github.event.after }}"
          echo "Compare: ${{ github.event.compare }}"
        shell: bash

#      - name: Push Changes
#        run: |
#            git push --force https://github.com/sanesh27/cicd_github_actions.git HEAD:version-check

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu latest
    steps:
      - name: Build apk
        run: |
          echo "The PR was merged"
          flutter build apk

      # Runs a set of commands using the runners shell
#      - name: Check flutter version
#        run: flutter build apk

# workflow for when a PR merged
#https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges