name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 3
  workflow_dispatch:

# 4
jobs:

#  version:
#    name: Create version number
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Install GitVersion
#        uses: gittools/actions/gitversion/setup@v0.9.7
#        with:
#          versionSpec: "5.x"
#      - name: Use GitVersion
#        id: gitversion
#        uses: gittools/actions/gitversion/execute@v0.9.7
#      - name: Create version.txt with nuGetVersion
#        run: echo ${{ steps.gitversion.outputs.nuGetVersion }} > version.txt
#      - name: Upload version.txt
#        uses: actions/upload-artifact@v2
#        with:
#          name: gitversion
#          path: version.txt

  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      #8
      - uses: actions/checkout@v3

      #9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Dart format
        run: dart format .

      - name: Commit and push identation
        run: |
          git config user.name "sanesh27"
          git config user.email "sanish.maharjan27@gmail.com"
          git add .
          git commit -m "Update: code format"
        shell: bash

      - name: Push Changes
          run: |
            git push --force https://github.com/sanesh27/cicd_github_actions.git HEAD:master 

      # Runs a set of commands using the runners shell
#      - name: Check flutter version
#        run: flutter build apk