name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      #8
      - uses: actions/checkout@v3

      #9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Dart format
        run: |
        if dart format --set-exit-if-changed .; then
        echo "Indentation check passed."
        else
        echo "Indentation check failed. Please run 'dart format' to fix code formatting issues."
        exit 1

      # Runs a set of commands using the runners shell
      - name: Check flutter version
        run: flutter build apk